Added missing labels in "/src/locales/en.json" to remove Internationalization warnings  (#1z57ab9).
hotwax/reroute-fulfilment pull request #21
Opened 2022-01-28 12:46 UTC by meet-aniket

2022-02-03 05:25 UTC, ymaheshwari1 requested changes

2022-02-03 05:25 UTC, ymaheshwari1 commented on changelogs/unreleased/-1z57ab9.yml
> +title: added missing labels in /src/locales/en.json (#1z57ab9).
Remove branch name from title

2022-02-03 05:39 UTC, meet-aniket commented on changelogs/unreleased/-1z57ab9.yml
> +title: added missing labels in /src/locales/en.json (#1z57ab9).
Sure Sir removed.

2022-02-03 05:44 UTC, ymaheshwari1 approved these changes

2022-02-07 05:01 UTC, adityasharma7 approved these changes

2022-02-07 05:01 UTC, merged