Improved: Migrated from moment timezone to luxon timezone(#2dewerv)
hotwax/reroute-fulfilment pull request #35
Opened 2022-07-05 13:08 UTC by shashwatbangar

# Related Issues

### Closes #
https://github.com/hotwax/reroute-fulfilment/commit/313ab146d57743b7304283edd4b7ec36b37dad86

### Short Description and Why It's Useful

### Screenshots of Visual Changes before/after (If There Are Any)

### IMPORTANT NOTICE - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

 [✅] I read and followed [contribution rules](https://github.com/hotwax/job-manager#contribution-guideline)

2022-07-08 12:23 UTC, disha1202 requested changes

2022-07-08 12:23 UTC, disha1202 commented on package.json
>      "moment": "^2.29.1",
Remove moment.

2022-07-08 12:23 UTC, disha1202 commented on package.json
> +    "vue-loader-v16": "^16.0.0-beta.5.4"
Revert unwanted changes.

2022-07-08 12:23 UTC, disha1202 commented on src/main.ts
>      // TODO Use Loxon instead
We can remove this TODO now.

2022-07-08 13:07 UTC, shashwatbangar commented on package.json
> +    "vue-loader-v16": "^16.0.0-beta.5.4"
Done.

2022-07-08 13:07 UTC, shashwatbangar commented on src/components/ProductListItem.vue
> +    },
Fixed it.

2022-07-08 13:10 UTC, shashwatbangar commented on src/main.ts
>      // TODO Use Loxon instead
Done.

2022-08-30 06:23 UTC, disha1202 requested changes

2022-08-30 06:23 UTC, disha1202 commented on src/main.ts
> +    return DateTime.fromISO(value).toFormat(outFormat ? outFormat : 'MM-DD-YYYY');
```suggestion
    return DateTime.fromISO(value).toFormat(outFormat ? outFormat : 'MM-dd-yyyy');
```

2022-08-30 06:23 UTC, disha1202 commented on src/main.ts
> +    return DateTime.utc(value, inFormat).setZone(userProfile.userTimeZone).toFormat(outFormat ? outFormat : 'MM-DD-YYYY')
```suggestion
    return DateTime.utc(value, inFormat).setZone(userProfile.userTimeZone).toFormat(outFormat ? outFormat : 'MM-dd-yyyy')
```

2022-08-30 06:23 UTC, disha1202 commented on src/main.ts
>      const userProfile = store.getters['user/getUserProfile'];
Access the userTimeZone from state itself instead of using getters

2022-08-31 05:44 UTC, shashwatbangar commented on src/main.ts
> +    return DateTime.fromISO(value).toFormat(outFormat ? outFormat : 'MM-DD-YYYY');
Done.

2022-08-31 05:45 UTC, shashwatbangar commented on src/main.ts
> +    return DateTime.utc(value, inFormat).setZone(userProfile.userTimeZone).toFormat(outFormat ? outFormat : 'MM-DD-YYYY')
Done.

2023-04-27 05:31 UTC, closed without merging