Added: favicon and manifest.json file
hotwax/reroute-fulfilment pull request #88
Opened 2024-06-21 12:54 UTC by Sandesh3003

### Related Issues

#87 

### Short Description and Why It's Useful

Added favicon and manifest.json file to display dedicated favicon for reroute fulfilment application.

### Screenshots of Visual Changes before/after (If There Are Any)

![image](https://github.com/hotwax/reroute-fulfilment/assets/77960808/02737bbe-0211-4ce6-9db2-a64a4a2c81ba)

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules]

2024-06-21 13:05 UTC, amansinghbais commented on manifest.json
> +    "name": "Reroute Fulfilment Application",
```suggestion
    "name": "Hotwax Commerce Reroute Fulfilment",
```

2024-06-21 13:05 UTC, amansinghbais commented on manifest.json
> +    "short_name": "Reroute",
```suggestion
    "short_name": "Reroute Fulfilment",
```

2024-06-25 11:21 UTC, ymaheshwari1 requested changes

2024-06-25 11:21 UTC, ymaheshwari1 commented on manifest.json
> +    "name": "Hotwax Commerce Reroute Fulfilment",
Improve indentation to 2 spaces as followed in the app

2024-06-25 13:14 UTC, ymaheshwari1 approved these changes

2024-06-25 13:16 UTC, merged